### ISSUE TITLE
More one example using ExNcurses

### ISSUE THREAD

**Issue by MarceloMPJ** [jfreeze/ex_ncurses#17]
Hi!
I created a mini game using `ExNcurses` too.
You can add he into `README.md`?

Link to my project: [Spacelixir](https://github.com/MarceloMPJ/Spacelixir)

**Comment by fhunleth** [comment]
That's awesome!

**Comment by fhunleth** [comment]
Could you make a PR that adds it to the example list?

**Comment by MarceloMPJ** [comment]
Yeap :+1:

**Comment by fhunleth** [comment]
Fixed by #18
